name: Pull Request

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  build:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17.x'
      - run: yarn install
      - run: yarn lint
      - run: yarn test